version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: goMs
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:3.4
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  zookeeper:
    image: zookeeper:3.7.1
    ports:
      - "2181:2181"

  myservice:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: goMs
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: mytopic
      ZOOKEEPER_HOST: zookeeper
#      DATABASE_URL: postgres://postgres:12345678@postgres:5432/goMs
    depends_on:
      - db
      - kafka
